package pe.com.mmh.sisgap.domain;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SisgapServicios generated by hbm2java
 */
@Entity
@Table(name="SISGAP_SERVICIOS"
    ,schema="SISGAP"
)
public class Servicios  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
    @Column(name="COD_SERVICIO", unique=true, nullable=false, precision=22, scale=0)
     private BigDecimal codServicio;
     @Column(name="NRO_SERVICIO", precision=10, scale=0)
     private Long nroServicio;
    @Column(name="NUM_TOTAL", precision=11)
     private BigDecimal numTotal;
    @Column(name="STR_DESCRIPCION", length=100)
     private String strDescripcion;
    @Column(name="NUM_ESTADO", precision=1, scale=0)
     private BigDecimal numEstado;
    @Temporal(TemporalType.DATE)
    @Column(name="DAT_FECHACREA", length=7)
     private Date datFechacrea;
    @Temporal(TemporalType.DATE)
    @Column(name="DAT_FECHASERV", length=7)
     private Date datFechaserv;
    @Column(name="STR_MONEDA", length=20)
     private String strMoneda;
	@OneToMany(mappedBy="sisgapServicios", fetch=FetchType.EAGER)
	private List<ServicioDetalle> sisgapServicioDetalle;
    
    public List<ServicioDetalle> getSisgapServicioDetalle() {
		return sisgapServicioDetalle;
	}

	public void setSisgapServicioDetalle(List<ServicioDetalle> sisgapServicioDetalle) {
		this.sisgapServicioDetalle = sisgapServicioDetalle;
	}

	public Servicios() {
    }

	
    public Servicios(BigDecimal codServicio) {
        this.codServicio = codServicio;
    }
    public Servicios(BigDecimal codServicio, Long nroServicio, BigDecimal numTotal, String strDescripcion, BigDecimal numEstado, Date datFechacrea, Date datFechaserv, String strMoneda) {
       this.codServicio = codServicio;
       this.nroServicio = nroServicio;
       this.numTotal = numTotal;
       this.strDescripcion = strDescripcion;
       this.numEstado = numEstado;
       this.datFechacrea = datFechacrea;
       this.datFechaserv = datFechaserv;
       this.strMoneda = strMoneda;
    }
   
         public BigDecimal getCodServicio() {
        return this.codServicio;
    }
    
    public void setCodServicio(BigDecimal codServicio) {
        this.codServicio = codServicio;
    }
    
    
    public Long getNroServicio() {
        return this.nroServicio;
    }
    
    public void setNroServicio(Long nroServicio) {
        this.nroServicio = nroServicio;
    }
    
        public BigDecimal getNumTotal() {
        return this.numTotal;
    }
    
    public void setNumTotal(BigDecimal numTotal) {
        this.numTotal = numTotal;
    }
    
        public String getStrDescripcion() {
        return this.strDescripcion;
    }
    
    public void setStrDescripcion(String strDescripcion) {
        this.strDescripcion = strDescripcion;
    }
    
    public BigDecimal getNumEstado() {
        return this.numEstado;
    }
    
    public void setNumEstado(BigDecimal numEstado) {
        this.numEstado = numEstado;
    }
        public Date getDatFechacrea() {
        return this.datFechacrea;
    }
    
    public void setDatFechacrea(Date datFechacrea) {
        this.datFechacrea = datFechacrea;
    }
        public Date getDatFechaserv() {
        return this.datFechaserv;
    }
    
    public void setDatFechaserv(Date datFechaserv) {
        this.datFechaserv = datFechaserv;
    }
    
        public String getStrMoneda() {
        return this.strMoneda;
    }
    
    public void setStrMoneda(String strMoneda) {
        this.strMoneda = strMoneda;
    }




}