package pe.com.mmh.sisgap.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SisgapServicioitem generated by hbm2java
 */
@Entity
@Table(name="SISGAP_SERVICIOITEM"
    ,schema="SISGAP"
)
public class ServicioItem  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
    @Column(name="COD_SERVICIOITEM", unique=true, nullable=false, precision=22, scale=0)
     private BigDecimal codServicioitem;
     @Column(name="STR_DESCRIPCION", length=200)
     private String strDescripcion;
    @Column(name="NUM_COSTO", precision=8)
     private BigDecimal numCosto;
    @Column(name="NUM_ESTADO", precision=1, scale=0)
     private Boolean numEstado;
    @Column(name="DAT_FECHACREA")
     private Serializable datFechacrea;

    public ServicioItem() {
    }

	
    public ServicioItem(BigDecimal codServicioitem) {
        this.codServicioitem = codServicioitem;
    }
    public ServicioItem(BigDecimal codServicioitem, String strDescripcion, BigDecimal numCosto, Boolean numEstado, Serializable datFechacrea) {
       this.codServicioitem = codServicioitem;
       this.strDescripcion = strDescripcion;
       this.numCosto = numCosto;
       this.numEstado = numEstado;
       this.datFechacrea = datFechacrea;
    }
   
         public BigDecimal getCodServicioitem() {
        return this.codServicioitem;
    }
    
    public void setCodServicioitem(BigDecimal codServicioitem) {
        this.codServicioitem = codServicioitem;
    }
    
    
    public String getStrDescripcion() {
        return this.strDescripcion;
    }
    
    public void setStrDescripcion(String strDescripcion) {
        this.strDescripcion = strDescripcion;
    }
    
        public BigDecimal getNumCosto() {
        return this.numCosto;
    }
    
    public void setNumCosto(BigDecimal numCosto) {
        this.numCosto = numCosto;
    }
    
        public Boolean getNumEstado() {
        return this.numEstado;
    }
    
    public void setNumEstado(Boolean numEstado) {
        this.numEstado = numEstado;
    }
    
        public Serializable getDatFechacrea() {
        return this.datFechacrea;
    }
    
    public void setDatFechacrea(Serializable datFechacrea) {
        this.datFechacrea = datFechacrea;
    }




}