package pe.com.mmh.sisgap.domain;
// Generated 28/08/2012 12:11:04 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SisgapReunionesSocio generated by hbm2java
 */
@Entity
@Table(name = "SISGAP_REUNIONES_SOCIO", schema = "SISGAP")
public class SisgapReunionesSocio implements java.io.Serializable {
private static final long serialVersionUID = 1L;

    private BigDecimal codigocorrelativo;
    private BigDecimal codigoreuniones;
    private String codigosocios;
    private Date fechaasamblea;
    private Date fechaingreso;
    private BigDecimal estado;
    private String usuario;
    private String observaciones;

    public SisgapReunionesSocio() {
    }

    public SisgapReunionesSocio(BigDecimal codigocorrelativo) {
        this.codigocorrelativo = codigocorrelativo;
    }

    public SisgapReunionesSocio(BigDecimal codigocorrelativo, BigDecimal codigoreuniones, String codigosocios, Date fechaasamblea, Date fechaingreso, BigDecimal estado, String usuario, String observaciones) {
        this.codigocorrelativo = codigocorrelativo;
        this.codigoreuniones = codigoreuniones;
        this.codigosocios = codigosocios;
        this.fechaasamblea = fechaasamblea;
        this.fechaingreso = fechaingreso;
        this.estado = estado;
        this.usuario = usuario;
        this.observaciones = observaciones;
    }

    @Id
    @Column(name = "CODIGOCORRELATIVO", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getCodigocorrelativo() {
        return this.codigocorrelativo;
    }

    public void setCodigocorrelativo(BigDecimal codigocorrelativo) {
        this.codigocorrelativo = codigocorrelativo;
    }

    @Column(name = "CODIGOREUNIONES", precision = 22, scale = 0)
    public BigDecimal getCodigoreuniones() {
        return this.codigoreuniones;
    }

    public void setCodigoreuniones(BigDecimal codigoreuniones) {
        this.codigoreuniones = codigoreuniones;
    }

    @Column(name = "CODIGOSOCIOS", length = 20)
    public String getCodigosocios() {
        return this.codigosocios;
    }

    public void setCodigosocios(String codigosocios) {
        this.codigosocios = codigosocios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHAASAMBLEA", length = 7)
    public Date getFechaasamblea() {
        return this.fechaasamblea;
    }

    public void setFechaasamblea(Date fechaasamblea) {
        this.fechaasamblea = fechaasamblea;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHAINGRESO", length = 7)
    public Date getFechaingreso() {
        return this.fechaingreso;
    }

    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }

    @Column(name = "ESTADO", precision = 22, scale = 0)
    public BigDecimal getEstado() {
        return this.estado;
    }

    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }

    @Column(name = "USUARIO", length = 20)
    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    @Column(name = "OBSERVACIONES", length = 200)
    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
}
