package pe.com.mmh.sisgap.domain;
// Generated 17/08/2012 12:12:01 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SisgapReuniones generated by hbm2java
 */
@Entity
@Table(name="SISGAP_REUNIONES"
    ,schema="SISGAP"
)
public class SisgapReuniones  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

     private BigDecimal numCodReuniones;
     private Date datFechaSesion;
     private String strLugar;
     private String strAgenda;
     private String strAcuerdos;
     private String strObservaciones;
     private BigDecimal numEstado;
     private Date datFechaIngreso;
     private String strUsuario;

    public SisgapReuniones() {
    }

	
    public SisgapReuniones(BigDecimal numCodReuniones) {
        this.numCodReuniones = numCodReuniones;
    }
    public SisgapReuniones(BigDecimal numCodReuniones, Date datFechaSesion, String strLugar, String strAgenda, String strAcuerdos, String strObservaciones, BigDecimal numEstado, Date datFechaIngreso) {
       this.numCodReuniones = numCodReuniones;
       this.datFechaSesion = datFechaSesion;
       this.strLugar = strLugar;
       this.strAgenda = strAgenda;
       this.strAcuerdos = strAcuerdos;
       this.strObservaciones = strObservaciones;
       this.numEstado = numEstado;
       this.datFechaIngreso = datFechaIngreso;
    }
   
     @Id 
    
    @Column(name="NUM_COD_REUNIONES", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getNumCodReuniones() {
        return this.numCodReuniones;
    }
    
    public void setNumCodReuniones(BigDecimal numCodReuniones) {
        this.numCodReuniones = numCodReuniones;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DAT_FECHA_SESION", length=7)
    public Date getDatFechaSesion() {
        return this.datFechaSesion;
    }
    
    public void setDatFechaSesion(Date datFechaSesion) {
        this.datFechaSesion = datFechaSesion;
    }
    
    @Column(name="STR_LUGAR", length=200)
    public String getStrLugar() {
        return this.strLugar;
    }
    
    public void setStrLugar(String strLugar) {
        this.strLugar = strLugar;
    }
    
    @Column(name="STR_AGENDA", length=200)
    public String getStrAgenda() {
        return this.strAgenda;
    }
    
    public void setStrAgenda(String strAgenda) {
        this.strAgenda = strAgenda;
    }
    
    @Column(name="STR_ACUERDOS", length=200)
    public String getStrAcuerdos() {
        return this.strAcuerdos;
    }
    
    public void setStrAcuerdos(String strAcuerdos) {
        this.strAcuerdos = strAcuerdos;
    }
    
    @Column(name="STR_OBSERVACIONES", length=200)
    public String getStrObservaciones() {
        return this.strObservaciones;
    }
    
    public void setStrObservaciones(String strObservaciones) {
        this.strObservaciones = strObservaciones;
    }
    
    @Column(name="NUM_ESTADO", precision=22, scale=0)
    public BigDecimal getNumEstado() {
        return this.numEstado;
    }
    
    public void setNumEstado(BigDecimal numEstado) {
        this.numEstado = numEstado;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DAT_FECHA_INGRESO", length=7)
    public Date getDatFechaIngreso() {
        return this.datFechaIngreso;
    }
    
    public String getStrUsuario() {
		return strUsuario;
	}


	public void setStrUsuario(String strUsuario) {
		this.strUsuario = strUsuario;
	}


	public void setDatFechaIngreso(Date datFechaIngreso) {
        this.datFechaIngreso = datFechaIngreso;
    }




}


